apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-gce-pd-mongo
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard
  replication-type: regional-pd
volumeBindingMode: Immediate
allowedTopologies:
- matchLabelExpressions:
  - key: topology.gke.io/zone
    values:
    - asia-south1-a
    - asia-south1-b
